# Generated by Django 4.2.1 on 2024-05-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'El correo electrónico ingresado ya está en uso.'}, max_length=255, unique=True, verbose_name='Correo Electrónico'),
        ),
    ]
